AWSTemplateFormatVersion: '2010-09-09'

Resources:
  PrismDemoTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08e2d37b6a0129927
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref HTTPSecurityGroup
      Tags:
        - Key: git_modifiers
          Value: pvondemhagen
        - Key: git_last_modified_by
          Value: pvondemhagen@yahoo.com
        - Key: git_last_modified_at
          Value: "2023-02-02 18:25:40"
        - Key: git_file
          Value: test-stack.yaml
        - Key: git_commit
          Value: 6cf903caad10c2d01f2d78ac0401123419c06fb7
        - Key: yor_trace
          Value: 49ad8d3c-a704-4659-9be0-475469021c44
        - Key: git_repo
          Value: aws_cloud_formation_4
        - Key: git_org
          Value: pvondemhagen
  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable port 80  and port 443
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      Tags:
        - Key: git_repo
          Value: aws_cloud_formation_4
        - Key: git_org
          Value: pvondemhagen
        - Key: git_modifiers
          Value: pvondemhagen
        - Key: git_last_modified_by
          Value: pvondemhagen@yahoo.com
        - Key: git_last_modified_at
          Value: "2023-02-02 18:25:40"
        - Key: git_file
          Value: test-stack.yaml
        - Key: git_commit
          Value: 6cf903caad10c2d01f2d78ac0401123419c06fb7
        - Key: yor_trace
          Value: f9514e46-772a-46fc-89dd-b44b47408568